In [1]:
import numpy as np 

In [2]:
array = np.array([1,2,3,4,5,6], dtype='int')
array


array([1, 2, 3, 4, 5, 6])

In [6]:
type(array)
array.dtype

dtype('int32')

In [7]:
array2 = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]], dtype='int', ndmin=2)
array2

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

In [8]:
array3 = np.array([1,2,3], dtype= 'complex')
array3

array([1.+0.j, 2.+0.j, 3.+0.j])

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [14]:
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
a.reshape((5,2))
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])