In [31]:
import numpy as np
import numpy.ma as ma

## Ejercicio 1.
Crea 3 nuevos arrays.
- Array de tipo entero, que contenga los numeros impares del 1 al 100.
- Array de tipo cadena, con tu nombre y apellidos.
- Array de tipo fecha, que contenga todos los dias desde el 01Enero2020 al 04Febrero2020.


In [3]:
a = np.arange(1,101,2, dtype='int')
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [10]:
b = np.array(['Alejandro Roman','Gonzalez','Jurado'])
b

array(['Alejandro Roman', 'Gonzalez', 'Jurado'], dtype='<U15')

In [9]:
c = np.arange('2020-01-01','2020-02-04',dtype='datetime64[D]')
c

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
       '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
       '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12',
       '2020-01-13', '2020-01-14', '2020-01-15', '2020-01-16',
       '2020-01-17', '2020-01-18', '2020-01-19', '2020-01-20',
       '2020-01-21', '2020-01-22', '2020-01-23', '2020-01-24',
       '2020-01-25', '2020-01-26', '2020-01-27', '2020-01-28',
       '2020-01-29', '2020-01-30', '2020-01-31', '2020-02-01',
       '2020-02-02', '2020-02-03'], dtype='datetime64[D]')

## Ejercicio 2. 
Recupera los ultimos 10 elementos del array de impares.

In [21]:
a[-10:]

array([81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

## Ejercicio 3.
Recorre el array de fechas, y genera un nuevo numpy array que contenga unicamente los dias laborables.

In [25]:
array = []
for f in c:
    if np.is_busday(f):
        array.append(f)
laborables = np.array(array, dtype='datetime64')
laborables


array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-06',
       '2020-01-07', '2020-01-08', '2020-01-09', '2020-01-10',
       '2020-01-13', '2020-01-14', '2020-01-15', '2020-01-16',
       '2020-01-17', '2020-01-20', '2020-01-21', '2020-01-22',
       '2020-01-23', '2020-01-24', '2020-01-27', '2020-01-28',
       '2020-01-29', '2020-01-30', '2020-01-31', '2020-02-03'],
      dtype='datetime64[D]')

## Ejercicio 4
Genera la siguiente matriz.
¿De que tipo es? Implementa una máscara a todos los numeros mayores o iguales a 10.

In [35]:
m = np.array([[10,1,8,4],[3,7,2,1],[0,2,20,12]], dtype=np.int16)
matriz = np.matrix('10 1 8 4; 3 7 2 1; 0 2 20 12', dtype=np.int16)
matriz


matrix([[10,  1,  8,  4],
        [ 3,  7,  2,  1],
        [ 0,  2, 20, 12]], dtype=int16)

In [36]:
ma.masked_where(matriz>=10, matriz)

masked_matrix(
  data=[[--, 1, 8, 4],
        [3, 7, 2, 1],
        [0, 2, --, --]],
  mask=[[ True, False, False, False],
        [False, False, False, False],
        [False, False,  True,  True]],
  fill_value=999999,
  dtype=int16)

## Ejercicio 5.
Crea dos fechas, la primera de ella será tu fecha de nacimiento, y la segunda, la de un familiar o amigo tuyo.

- ¿Qué diferencia de horas hay entre esas dos fechas?
- ¿Cuál sería tu fecha de nacimiento si hubieras nacido 236 horas antes?
  

In [37]:
f_ale = np.datetime64('2002-11-26')
f_sergi = np.datetime64('2002-10-31')


In [39]:
dif = f_ale - f_sergi
np.timedelta64(dif,'h') 

numpy.timedelta64(624,'h')

In [40]:
nac_ant = f_ale - np.timedelta64(236,'h')
nac_ant

numpy.datetime64('2002-11-16T04','h')