Indexado y recorrido.

In [1]:
import numpy as np

In [2]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a[4]

4

In [5]:
a.shape

(10,)

In [10]:
a[9]

9

Slicing

In [8]:
a[0:9:2]

array([0, 2, 4, 6, 8])

In [9]:
a[-2:10]

array([8, 9])

In [11]:
a[9::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Consultar arrays multidimensionales.

In [13]:
a = np.array([[1,2,3],[3,4,5]], dtype=np.int8)
a

array([[1, 2, 3],
       [3, 4, 5]], dtype=int8)

In [15]:
a[0][0]

1

In [16]:
a[1][2]

5

In [17]:
a[1,2]

5

In [18]:
a[1,0:2]

array([3, 4], dtype=int8)

In [19]:
a[0:2,0:2]

array([[1, 2],
       [3, 4]], dtype=int8)

In [20]:
m = np.matrix(a)
m

matrix([[1, 2, 3],
        [3, 4, 5]], dtype=int8)

In [22]:
m[0,1] + m[1,0]

5

In [23]:
x = np.array([[4,3], [np.nan, 2.], [np.nan, np.nan]])
x

array([[ 4.,  3.],
       [nan,  2.],
       [nan, nan]])

In [24]:
x[np.isnan(x)]

array([nan, nan, nan])

In [25]:
x[~np.isnan(x)]

array([4., 3., 2.])

Indexado booleano

In [26]:
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
a > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [28]:
a[a>4]

array([5, 6, 7, 8, 9])

In [29]:
a[a%2 == 0]

array([0, 2, 4, 6, 8])

In [30]:
char_array = np.array(['OpenWebinars','Machine Learning','Numpy'])
char_array

array(['OpenWebinars', 'Machine Learning', 'Numpy'], dtype='<U16')

In [31]:
char_array == 'Numpy'

array([False, False,  True])

In [32]:
char_array[char_array == 'Numpy']

array(['Numpy'], dtype='<U16')