In [1]:
import numpy as np 
import numpy.ma as ma

In [2]:
x = np.array([1,2,3,-1,4])
x

array([ 1,  2,  3, -1,  4])

In [3]:
mask_array = ma.masked_array(x , mask = [0,0,0,1,0])
mask_array

masked_array(data=[1, 2, 3, --, 4],
             mask=[False, False, False,  True, False],
       fill_value=999999)

In [4]:
x.min()

-1

In [5]:
mask_array.min()

1

In [6]:
x = ma.array([1,2,3,-1,4], mask = [0,0,0,1,0])
x

masked_array(data=[1, 2, 3, --, 4],
             mask=[False, False, False,  True, False],
       fill_value=999999)

In [7]:
x.compressed()

array([1, 2, 3, 4])

In [8]:
x.mask = True
x

masked_array(data=[--, --, --, --, --],
             mask=[ True,  True,  True,  True,  True],
       fill_value=999999,
            dtype=int32)

In [9]:
x.mask = False 
x

masked_array(data=[1, 2, 3, -1, 4],
             mask=[False, False, False, False, False],
       fill_value=999999)

In [10]:
x.mask = [0,0,0,1,0]
x

masked_array(data=[1, 2, 3, --, 4],
             mask=[False, False, False,  True, False],
       fill_value=999999)

In [11]:
x[0] is ma.masked

False

In [12]:
x[3] is ma.masked

True

Rellena los datos nulos con el numero que introducimos.

In [14]:
x.filled(0)


array([1, 2, 3, 0, 4])

In [15]:
x = np.array([1,2,3,-1,4])
x

array([ 1,  2,  3, -1,  4])

Formas de enmascarar.

In [16]:
ma.masked_equal(x,4)

masked_array(data=[1, 2, 3, -1, --],
             mask=[False, False, False, False,  True],
       fill_value=4)

In [17]:
ma.masked_not_equal(x,2)

masked_array(data=[--, 2, --, --, --],
             mask=[ True, False,  True,  True,  True],
       fill_value=999999)

In [18]:
ma.masked_where(x<2,x)

masked_array(data=[--, 2, 3, --, 4],
             mask=[ True, False, False,  True, False],
       fill_value=999999)

In [19]:
ma.masked_greater_equal(x,2)

masked_array(data=[1, --, --, -1, --],
             mask=[False,  True,  True, False,  True],
       fill_value=999999)

In [20]:
ma.masked_less_equal(x,3)

masked_array(data=[--, --, --, --, 4],
             mask=[ True,  True,  True,  True, False],
       fill_value=999999)

In [21]:
ma.masked_inside(x,1,3)

masked_array(data=[--, --, --, -1, 4],
             mask=[ True,  True,  True, False, False],
       fill_value=999999)