In [12]:
import numpy as np
from sys import getsizeof

In [2]:
a = np.array([1,2,3,4,5], dtype=np.int_)
a

array([1, 2, 3, 4, 5])

In [3]:
a.dtype

dtype('int32')

In [9]:
bool_array = np.array([[1,0,0,1],[0,1,1,0]], dtype=np.bool_)
bool_array

array([[ True, False, False,  True],
       [False,  True,  True, False]])

In [10]:
True * True

1

In [11]:
char_array = np.array(['a','b','c'], dtype=np.chararray)
char_array

array(['a', 'b', 'c'], dtype=object)

In [13]:
a = np.array([1,2,3,4], dtype=np.int8)
b = np.array([1,2,3,4], dtype=np.int64)

print('A', getsizeof(a))
print('B', getsizeof(b))

A 116
B 144


In [14]:
a.dtype.type is np.int8

True

Nan

In [15]:
#np.nan
np.nan

nan

In [17]:
#Saber si un dato es Nan.
np.isnan(np.nan)

True

In [18]:
np.array([1,2,3,np.nan,4])

array([ 1.,  2.,  3., nan,  4.])

## Matriz

In [22]:
m = np.matrix('1 2 3 ; 4 5 6', dtype=np.float16)
m

matrix([[1., 2., 3.],
        [4., 5., 6.]], dtype=float16)

In [24]:
a = np.array([[1,2,3],[4,5,6]], dtype=np.float16)
a

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float16)

In [25]:
m = np.asmatrix(a)
m

matrix([[1., 2., 3.],
        [4., 5., 6.]], dtype=float16)