In [1]:
import numpy as np 

In [2]:
a = np.array ([[3,2],[1,3]])
b = np.array ([[2,2],[1,2]])

Multiplicaciones de matrices.

In [3]:
np.dot(a,b)

array([[ 8, 10],
       [ 5,  8]])

In [4]:
np.dot(b,a)

array([[ 8, 10],
       [ 5,  8]])

Producto escalar

In [5]:
np.vdot(a,b)

17

In [7]:
a = np.arange(6).reshape((2,3))
b = np.arange(3)
print(a)
print(b)

[[0 1 2]
 [3 4 5]]
[0 1 2]


Producto interno

In [8]:
np.inner(a,b)

array([ 5, 14])

Elevar a un numero.

In [9]:
m = np.array([[2,3],[1,4]])
m

array([[2, 3],
       [1, 4]])

In [10]:
np.linalg.matrix_power(m,2)

array([[ 7, 18],
       [ 6, 19]])

In [11]:
np.dot(m,m)

array([[ 7, 18],
       [ 6, 19]])

### Calcular valores propios, determinantes y vectores propios.

In [14]:
m = np.diag([4,3,2,1])
m

array([[4, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 1]])

Valor propio

In [15]:
np.linalg.eig(m)

EigResult(eigenvalues=array([4., 3., 2., 1.]), eigenvectors=array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]]))

Determinante

In [16]:
np.linalg.det(m)

24.000000000000004

Resolucion de ecuaciones

In [19]:
a = np.array([[3,1],[1,2]])
b = np.array([9,8])
print(a)
print(b)

[[3 1]
 [1 2]]
[9 8]


In [20]:
#Funcionaria de forma que la primera ecuacion es 3x + 1y = 9 y x + 2y = 8.
x = np.linalg.solve(a,b)
x

array([2., 3.])