In [1]:
import numpy as np

### Ejercicios 3.

Ejercicio 1:

Usando el array que encontráis a continuación.

- ¿Hay algún valor múltiplo de 7?
- Devuelve un array con todos los nº menores de 40 o que sean múltiplos de 7

In [2]:
a = np.array([2, 5, 4, 2, 49, 34, 59, 21, 45, 6, 105])

In [3]:
np.any(a % 7 == 0)

True

In [4]:
np.logical_or(a % 7 == 0, a<40)

array([ True,  True,  True,  True,  True,  True, False,  True, False,
        True,  True])

In [5]:
res = a[np.logical_or(a % 7 == 0, a<40)]
res

array([  2,   5,   4,   2,  49,  34,  21,   6, 105])

Ejercicio 2:

Usando el array resultado del ejercicio anterior, calcula:

- El producto de todos sus valores.
- Convierte el array el una matriz 3x3 y realiza la suma por filas.
- Calcula el log10 de cada elemento de la matriz que acabas de crear.

In [6]:
res

array([  2,   5,   4,   2,  49,  34,  21,   6, 105])

In [7]:
np.prod(res)

1763294400

In [11]:
res_t = res.T.reshape(3,3)
suma = np.sum(res_t, axis=1)
suma

array([ 11,  85, 132])

In [10]:
np.log10(res_t)

array([[0.30103   , 0.69897   , 0.60205999],
       [0.30103   , 1.69019608, 1.53147892],
       [1.32221929, 0.77815125, 2.0211893 ]])

Ejercicio 3:

Haciendo uso de la matriz 3x3 creada en el ejercicio anterior y del siguiente array a, calcule:

- La suma de la matriz más el vector.
- La división de ambos. ¿qué ocurre? Modifique el valor extraño por 0.
- El valor máximo de la matriz resultado de la división. ¿y por filas? ¿y por columnas?

In [13]:
a = np.array([0,3,5])
print(res_t)
print(a)

[[  2   5   4]
 [  2  49  34]
 [ 21   6 105]]
[0 3 5]


In [14]:
suma = np.add(res_t, a)
suma

array([[  2,   8,   9],
       [  2,  52,  39],
       [ 21,   9, 110]])

In [15]:
division = np.divide(res_t,a)
division

C:\Users\Alex\AppData\Local\Temp\ipykernel_9836\1638868696.py:1: RuntimeWarning: divide by zero encountered in divide
  division = np.divide(res_t,a)


array([[        inf,  1.66666667,  0.8       ],
       [        inf, 16.33333333,  6.8       ],
       [        inf,  2.        , 21.        ]])

In [17]:
division[np.isinf(division)] = 0
division

array([[ 0.        ,  1.66666667,  0.8       ],
       [ 0.        , 16.33333333,  6.8       ],
       [ 0.        ,  2.        , 21.        ]])

In [18]:
max = np.max(division)
max

21.0

In [19]:
max = np.max(division, axis=1)
max

array([ 1.66666667, 16.33333333, 21.        ])

In [20]:
max = np.max(division, axis=0)
max

array([ 0.        , 16.33333333, 21.        ])

Ejercicio 4:

Considerando el array de números que podéis encontrar justo arriba, calcula:

- Valor medio y mediano.
- ¿Qué valor se encuentra en el tercer cuártil?
- ¿Qué valor se encuentra en el percentil 25? ¿y en el 50? ¿con qué valor coincide este último?
- ¿Cuál es la desviación estándar y la varianza del conjunto de datos?



In [21]:
array = np.array([44, 28,  8, 34, 34, 26, 32, 12, 28,  6, 19, 12, 46, 20, 20, 49, 18,
       19, 15, 15, 43,  3, 17, 33, 27, 10, 18,  2,  3,  3, 35, 35, 21, 17,
       36, 31, 16, 27,  6, 46, 29, 25, 26, 48, 30, 19, 18,  1, 43, 10, 32,
       15, 32, 30, 40, 41, 11, 46, 39,  5, 40,  1, 26, 10, 18, 26, 25, 25,
       21, 30, 12, 46,  1, 43,  1,  3, 26, 24,  0, 36, 34,  7, 26, 25, 41,
       22,  1, 16, 43,  1, 46, 14, 17, 39, 12,  9, 42, 48,  9, 45, 47, 32,
       15,  6, 40, 18,  6, 13, 35,  8, 46, 48, 26, 23, 12, 29, 21,  6,  3,
       22, 27, 16, 27, 10, 28, 23,  5, 24, 17, 43, 25, 11, 38, 40, 32, 42,
       27, 32,  6, 16, 18, 10, 18, 34, 34,  3,  4,  5,  4,  0, 35, 30,  9,
       16, 32, 46,  7, 10, 20, 13, 48,  8, 27, 27, 27, 16, 17, 12, 35, 31,
       21, 29, 15, 49, 14, 22, 18,  0, 13, 14, 39, 30,  4, 48,  1, 19, 33,
       39,  9,  0, 24,  6, 12, 24, 29, 16, 11, 12, 13, 11])

In [23]:
media = np.mean(array)
mediana = np.median(array)
print(media)
print(mediana)

22.405
21.0


In [24]:
tercer_q = np.quantile(array, q=0.75)
print(tercer_q) 

32.0


In [25]:
perc_25 = np.percentile(array, q=25)
perc_50 = np.percentile(array, q=50)
print(perc_25)
print(perc_50)

11.75
21.0


In [26]:
des = np.std(array)
var = np.var(array)
print(des)
print(var)

13.66934435150421
186.85097500000003
