In [2]:
import numpy as np

## Ejercicio 1.

Genera un array que contenga 25 elementos entre 0 y 99 usando una distribución lineal. Luego, transforma ese array en una matriz de 5x5.
¿Cuál es la diagonal de esa matriz?¿Y la diagonal justo superior?

In [39]:
a = np.linspace(start=0, stop=100, num=25, endpoint=False)
a

array([ 0.,  4.,  8., 12., 16., 20., 24., 28., 32., 36., 40., 44., 48.,
       52., 56., 60., 64., 68., 72., 76., 80., 84., 88., 92., 96.])

In [40]:
m = a.reshape(5,5)
m

array([[ 0.,  4.,  8., 12., 16.],
       [20., 24., 28., 32., 36.],
       [40., 44., 48., 52., 56.],
       [60., 64., 68., 72., 76.],
       [80., 84., 88., 92., 96.]])

In [41]:
np.diag(m)

array([ 0., 24., 48., 72., 96.])

In [42]:
np.diag(m, k=1)

array([ 4., 28., 52., 76.])

### Ejercicio 2

Crea un array de 4 x 5 con el valor repetido 10. Une esa matriz a la matriz del ejercicio anterior para conseguir dos nuevas matrices, una de 5 x 9, y otra de 9 x 5.

In [43]:
b = np.full(shape=(4,5), fill_value=[5])
b

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [44]:
m

array([[ 0.,  4.,  8., 12., 16.],
       [20., 24., 28., 32., 36.],
       [40., 44., 48., 52., 56.],
       [60., 64., 68., 72., 76.],
       [80., 84., 88., 92., 96.]])

In [45]:
np.concatenate((m,b), axis=0)

array([[ 0.,  4.,  8., 12., 16.],
       [20., 24., 28., 32., 36.],
       [40., 44., 48., 52., 56.],
       [60., 64., 68., 72., 76.],
       [80., 84., 88., 92., 96.],
       [ 5.,  5.,  5.,  5.,  5.],
       [ 5.,  5.,  5.,  5.,  5.],
       [ 5.,  5.,  5.,  5.,  5.],
       [ 5.,  5.,  5.,  5.,  5.]])

### Ejercicio 3.

Teniendo el array inicial que podéis ver justo abajo, debéis realizar las operaciones necesarias para obtener el array:

array(['Este', 'Es', 'Un', 'Curso', 'De', 'Openwebinars'], dtype='<U12')

¿Qué elementos del array comienzan por 'E'?

In [47]:
a = np.array([' este es un curso de openwebinars '])
a

array([' este es un curso de openwebinars '], dtype='<U34')

In [48]:
a1 = np.char.strip(a)
a1


array(['este es un curso de openwebinars'], dtype='<U34')

In [52]:
a2 = np.char.split(a1, sep=' ')
a2 = np.array(a2[0])
a2

array(['este', 'es', 'un', 'curso', 'de', 'openwebinars'], dtype='<U12')

In [54]:
a3 = np.char.capitalize(a2)
a3

array(['Este', 'Es', 'Un', 'Curso', 'De', 'Openwebinars'], dtype='<U12')

In [55]:
np.char.startswith(a3, prefix='E')

array([ True,  True, False, False, False, False])

### Ejercicio 4.

Considerando las matrices A y B.
- Realiza la multiplicación matricial de AxB y BxA. ¿Son iguales?
- Realiza la multiplicación de la matriz A x 2
- ¿Cúanto es la multiplicación escalar de AxB? ¿y de BxA?

In [17]:
a = np.array([[3,1,2],[4,1,3],[2,0,1]])
b = np.array([[2,0,3],[1,1,1],[0,2,4]])
print(a)
print(b)

[[3 1 2]
 [4 1 3]
 [2 0 1]]
[[2 0 3]
 [1 1 1]
 [0 2 4]]


In [18]:
np.dot(a,b)

array([[ 7,  5, 18],
       [ 9,  7, 25],
       [ 4,  2, 10]])

In [19]:
np.dot(b,a)

array([[12,  2,  7],
       [ 9,  2,  6],
       [16,  2, 10]])

In [20]:
np.dot(a,2)

array([[6, 2, 4],
       [8, 2, 6],
       [4, 0, 2]])

In [21]:
np.vdot(a,b)

24

In [22]:
np.vdot(b,a)

24

### Ejercicio 5.

Usando la matriz A del ejercicio anterior, calcula:
- A^3
- El determinante de A
- Resuelve la ecuación Ax = y, siendo *y* el array [3,2,5]

In [30]:
a = np.array([[3,1,2],[4,1,3],[2,0,1]])
a

array([[3, 1, 2],
       [4, 1, 3],
       [2, 0, 1]])

In [25]:
cubo = np.linalg.matrix_power(a,3)
print(cubo)

[[ 89  21  57]
 [114  27  73]
 [ 42  10  27]]


In [27]:
det = np.linalg.det(a)
det

1.0

In [29]:
y = np.array([3,2,5])



In [32]:
x = np.linalg.solve(a,y)
x

array([ 6., -1., -7.])