In [1]:
import numpy as np 

## Funciones lógicas.

In [2]:
a = np.array([2,3,4,5])

Comprueba que todos los elementos cumplen una condicion.

In [3]:
np.all(a<10)

True

Comprueba que existe un elemento que cumple una condicion. (ANY)

In [4]:
np.any( a < 3)

True

Funcion AND.

In [5]:
np.logical_and(a>2, a<4)

array([False,  True, False, False])

Funcion OR.

In [6]:
np.logical_or(a>2, a<4)

array([ True,  True,  True,  True])

Trabajamos con la tolerancia para valores chicos.

In [8]:
np.allclose([1e10,1e-7],[1.00001e10,1.000001e-7],rtol=0.00001)
#Respondera True por la tolerancia añadadida.

True

In [9]:
np.isclose([1e10,1e-7], [1.001e10,1.000001e-7], rtol=0.00001)

array([False,  True])

Menciona si dos arrays son iguales.

In [10]:
np.array_equal(np.array([1,2,3]), np.array([1,2,3]))

True

In [11]:
np.greater_equal(np.array([1,2,3]), np.array([1,20,3]))

array([ True, False,  True])

In [12]:
np.less_equal(np.array([1,2,3]), np.array([1,20,3]))

array([ True,  True,  True])