In [1]:
import numpy as np

### Funciones matemáticas.

Redondear (Escribimos el numero a la derecha)

In [2]:
a = 2.49264
a

2.49264

In [3]:
np.round(a, 2)

2.49

In [4]:
np.round(a,1)

2.5

In [5]:
array = np.array([1.435, 13.1435, 4.916])
np.round(array, 2)

array([ 1.44, 13.14,  4.92])

In [6]:
#Devuelve el entero mas pequeño.
np.floor(array)

array([ 1., 13.,  4.])

In [7]:
#Devuelve el entero mas grande.
np.ceil(array)

array([ 2., 14.,  5.])

Sumas y productos.

In [8]:
b = np.array([2,3,4])
np.prod(b)
#Producto de todo.

24

In [11]:
b = np.array([[2,3,4],[2,2,2]])
np.prod(b)
#Lo multiplica todo.

192

In [12]:
np.prod(b, axis=0)
#Multiplica filas.

array([4, 6, 8])

In [13]:
np.prod(b, axis=1)
#Multiplica columnas.

array([24,  8])

In [15]:
np.sum(b)
#Lo suma todo.

15

In [17]:
np.sum(b, axis=0)
#Al igual que prod, puede sumarse por filas o columnas.

array([4, 5, 6])

Exponentes y logaritmos.

In [18]:
b

array([[2, 3, 4],
       [2, 2, 2]])

In [19]:
np.exp(b)

array([[ 7.3890561 , 20.08553692, 54.59815003],
       [ 7.3890561 ,  7.3890561 ,  7.3890561 ]])

In [20]:
np.power(np.e, b)

array([[ 7.3890561 , 20.08553692, 54.59815003],
       [ 7.3890561 ,  7.3890561 ,  7.3890561 ]])

In [22]:
p = np.power(np.e,b)
p

array([[ 7.3890561 , 20.08553692, 54.59815003],
       [ 7.3890561 ,  7.3890561 ,  7.3890561 ]])

In [23]:
np.log(p)

array([[2., 3., 4.],
       [2., 2., 2.]])

In [24]:
np.log10(b)
#Logaritmos en base 10

array([[0.30103   , 0.47712125, 0.60205999],
       [0.30103   , 0.30103   , 0.30103   ]])

In [25]:
np.log2(b)
#Logaritmos en base 2

array([[1.       , 1.5849625, 2.       ],
       [1.       , 1.       , 1.       ]])

Operaciones aritmeticas.

In [26]:
a = np.array([[1,2,3,4], [4,3,2,1]])
b = np.array([4,3,2,1])

In [27]:
np.add(a,b)

array([[5, 5, 5, 5],
       [8, 6, 4, 2]])

In [28]:
np.subtract(a,b)

array([[-3, -1,  1,  3],
       [ 0,  0,  0,  0]])

In [29]:
np.multiply(a,b)

array([[ 4,  6,  6,  4],
       [16,  9,  4,  1]])

In [30]:
np.divide(a,b)

array([[0.25      , 0.66666667, 1.5       , 4.        ],
       [1.        , 1.        , 1.        , 1.        ]])