In [1]:
import numpy as np

### Operaciones estadísticas.

Funciones relacionadas con el orden.

In [2]:
a = np.array([2,5,6,10])
a

array([ 2,  5,  6, 10])

In [3]:
np.min(a)

2

In [4]:
np.max(a)

10

In [5]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
np.min(b,axis=0)
#Devuelve el minimo por columnas.

array([0, 1, 2, 3])

In [8]:
np.max(b, axis=1)
#Devuelve el maximo por filas.

array([ 3,  7, 11])

Percentiles y cuartiles.

In [10]:
b = np.arange(0,101)
b

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [11]:
np.percentile(b, q = 11)
#En q exponemos el percentil que queremos.

11.0

In [13]:
np.quantile(b, q=0.25)
#Los quantiles van de 0 a 1

25.0

Medias o varianzas.

In [14]:
#La media.
np.mean(b)

50.0

In [15]:
#La mediana.
np.median(b)

50.0

In [17]:
np.average(b)
#Otra funcion para la media.

50.0

In [18]:
b = np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [20]:
np.mean(b)

5.5

In [21]:
np.mean(b, axis=0)
#Medias por filas o por columnas.

array([4.5, 5.5, 6.5])

In [22]:
#La desviacion estandar.
np.std(b)

3.452052529534663

In [23]:
#La desviacion tipica.
np.var(b)

11.916666666666666