## Manipulación de Arrays

In [1]:
import numpy as np 

# Dimensiones del array.

In [2]:
a = np.array([[1,2,3,4],[4,3,2,1]])
#Conseguimos la dimensión de un array con shape.
a.shape

(2, 4)

In [3]:
a

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [4]:
#Podemos cambiar las dimensiones con reshape.
a.reshape((4,2))

array([[1, 2],
       [3, 4],
       [4, 3],
       [2, 1]])

In [5]:
#Muestra un array multidimensional como un array unidimensional.
a.ravel()

array([1, 2, 3, 4, 4, 3, 2, 1])

In [6]:
#Trasponer el array.
a.T

array([[1, 4],
       [2, 3],
       [3, 2],
       [4, 1]])

## Tipos de arrays.

In [8]:
#Convierte una lista Python en un array.
np.asarray([1,2,3,4,5], dtype=np.int8)

array([1, 2, 3, 4, 5], dtype=int8)

In [9]:
#Convierte una lista Python en un array de floats.
np.asfarray([1,2,3,4,5])

array([1., 2., 3., 4., 5.])

In [10]:
a = [1,2,3,4,5, np.nan]
a

[1, 2, 3, 4, 5, nan]

In [11]:
#Comprueba que nuestra lista no tenga infinitos ni nan. Devolverá error en caso contrario.
np.asarray_chkfinite(a)

ValueError: array must not contain infs or NaNs

In [12]:
#Genera un array repitiendo un numero un cantidad de veces concreta.
np.repeat(a = 99, repeats=10)

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [13]:
#Podemos darle forma con reshape.
np.repeat(a = 99, repeats=10).reshape((2,5))

array([[99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99]])

# Union de arrays.

In [14]:
a = np.array([[1,2,3,4],[1,2,3,4]])
b = np.array([[4,3,2,1]])
print(a.shape)
print(b.shape)

(2, 4)
(1, 4)


In [15]:
#Concatena dos arrays. Axis = 0 lo hace a nivel de filas, si está a 1, lo hace a nivel de columnas (siempre que coincidan.)
np.concatenate((a,b), axis=0)

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [4, 3, 2, 1]])

In [16]:
#Si lo trasponemos, podemos hacerlo por columnas.
np.concatenate((a.T,b.T), axis=1)
#Se puede utilizar np.stack de la misma forma que concatenate.

array([[1, 1, 4],
       [2, 2, 3],
       [3, 3, 2],
       [4, 4, 1]])

## Division de arrays.

In [17]:
a = np.arange(0,20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [18]:
#Divide el arrays por secciones.
np.split(a, indices_or_sections=4)

[array([0, 1, 2, 3, 4]),
 array([5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14]),
 array([15, 16, 17, 18, 19])]

In [19]:
#Podemos dividir por rangos.
np.split(a, [3,5,10,16])

[array([0, 1, 2]),
 array([3, 4]),
 array([5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14, 15]),
 array([16, 17, 18, 19])]

### Añadir y eliminar elementos de un array

In [21]:
a = np.array([[1,2,3,4]])
a

array([[1, 2, 3, 4]])

In [22]:
#Insertamos valores a partir de una posicion (obj).
np.insert(a, obj = 4, values=[5,6])

array([1, 2, 3, 4, 5, 6])

In [23]:
np.insert(a, obj = 1, values=[5,6])

array([1, 5, 6, 2, 3, 4])

In [24]:
#Append los insertará siempre al final.
np.append(a, [5,6])

array([1, 2, 3, 4, 5, 6])

In [25]:
#Para eliminar valores por posicion.
np.delete(a, obj=3)

array([1, 2, 3])

In [27]:
#Borra los ceros iniciales y finales, no los intermedios.
a = np.array([0,0,0,0,0,1,3,5,0,1,2,0,0,0])
np.trim_zeros(a)

array([1, 3, 5, 0, 1, 2])

In [29]:
#Simplifica el array y quita los valores repetidos.
a = np.array([1,1,1,1,2,2,2,3,3,3,1,2,3])
np.unique(a)

array([1, 2, 3])