## Operaciones con cadenas.

In [1]:
import numpy as np

Concatenamos arrays de cadenas.

In [3]:
a = np.array(['A','B','C'], dtype=np.str_)
b = np.array(['D','E','F'], dtype=np.str_)

np.char.add(a,b)

array(['AD', 'BE', 'CF'], dtype='<U2')

In [4]:
a

array(['A', 'B', 'C'], dtype='<U1')

In [5]:
#Multiplica los valores de a por los numeros indicados respectivamente.
np.char.multiply(a, [2,3,4])

array(['AA', 'BBB', 'CCCC'], dtype='<U4')

In [6]:
nombres = np.array(['maria','antonio','lucia'], dtype=np.str_)
nombres

array(['maria', 'antonio', 'lucia'], dtype='<U7')

In [7]:
#Pone los nombres en mayusculas.
np.char.capitalize(nombres)

array(['Maria', 'Antonio', 'Lucia'], dtype='<U7')

In [8]:
#Remplaza partes del array por otros.
np.char.replace(nombres, 'mar', 'sof')

array(['sofia', 'antonio', 'lucia'], dtype='<U7')

In [9]:
#Dividimos un array formado por una frase.
nombre = np.array(['Mi nombre es Alejandro Roman'])
np.char.split(nombre,sep = ' ')

array([list(['Mi', 'nombre', 'es', 'Alejandro', 'Roman'])], dtype=object)

In [10]:
#Borra los espacios de un array.
c = np.array(['    Hola    ', '    Adios    '])
np.char.strip(c)


array(['Hola', 'Adios'], dtype='<U13')

# Comparacion

In [11]:
#Devuelve un array de booleanos para comparar dos arrays.
a = np.array(['A','B','C'], dtype= np.str_)
b = np.array(['D','B','F'], dtype= np.str_)

np.char.equal(a,b)

array([False,  True, False])

In [12]:
np.char.not_equal(a,b)

array([ True, False,  True])

In [13]:
#Devuelve un array según su orden alfabetico.
np.char.greater_equal(a,b)

array([False,  True, False])

In [14]:
np.char.less_equal(a,b)

array([ True,  True,  True])

## Informacion de cadenas.

In [15]:
#Averiguar palabras que acaban en un sufijo.
c = np.array(['Hola','Adios'])

np.char.endswith(c, suffix='ios')

array([False,  True])

In [16]:
#Igual con prefijos. Ambos son key_sensitive (importan mayusculas y minusculas).
np.char.startswith(c, prefix='Ho')

array([ True, False])

In [17]:
c = np.array(['HOLA','adios'])
c

array(['HOLA', 'adios'], dtype='<U5')

In [18]:
#Comprueba que la palabra este en minuscula.
np.char.islower(c)

array([False,  True])

In [19]:
#Lo mismo en mayuscula.
np.char.isupper(c)

array([ True, False])

In [21]:
#Comprueba si hay digitos entre el array.
c = np.array(['Adios','Hola','1234'])
np.char.isdigit(c)

array([False, False,  True])

In [22]:
#Serviría para filtrados.
c[np.char.isdigit(c)]

array(['1234'], dtype='<U5')