In [1]:
import numpy as np 

In [2]:
#Matriz de con diagonal 1.
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [3]:
#K desplaza la diagonal.
np.eye(4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [4]:
#No puede desplazar la diagonal.
np.identity(4, dtype='int8')

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int8)

In [5]:
#Crea matriz con los valores que queramos.
np.full(shape=(4,4), fill_value=99)

array([[99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99]])

In [6]:
#Podemos pasarle una lista tambien.
np.full(shape=(4,4), fill_value=[10,20,30,40])

array([[10, 20, 30, 40],
       [10, 20, 30, 40],
       [10, 20, 30, 40],
       [10, 20, 30, 40]])

## Creacion desde datos existentes.

In [7]:
#Creacion.El "sep" indica mediante que los separa.
np.fromstring('1 2 3 4', sep=' ')

array([1., 2., 3., 4.])

In [8]:
#Crea a partir de un txt.
datos = np.loadtxt('./datos.txt', delimiter=' ')
datos

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

## Creacion de rangos numericos.

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
#Muesta 5 numeros que tengan la misma distanacia entre ellos en un rango.
np.linspace(start=1,stop=10, num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [11]:
#Endpoint hace que el valor final no pueda entrar en la matriz devuelta.
#Retstep devuelve el tamaño del paso.
np.linspace(start=1, stop=10, num=5, endpoint=False, retstep=True)

(array([1. , 2.8, 4.6, 6.4, 8.2]), 1.8)

In [12]:
#Hace un linspace de inicio a final, y eleva los valores al numero introducido en "num".
np.logspace(start=2, stop=3.5, num=10)

array([ 100.        ,  146.77992676,  215.443469  ,  316.22776602,
        464.15888336,  681.29206906, 1000.        , 1467.79926762,
       2154.43469003, 3162.27766017])

## Creación de matrices.

In [14]:
#Matriz basica.
a = np.eye(N = 4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
#Conseguir la diagonal.
np.diag(a)

array([1., 1., 1., 1.])

In [16]:
#K hace que desplace la diagonal.
np.diag(a, k=-1)

array([0., 0., 0.])

In [17]:
#Crear matrices a partir de solamente la diagonal. K desplaza la diagonal.
np.diagflat(v = [1,2,3,4,5,6], k=0)

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [18]:
#Crea matrices NxM cuya parte inferior a la diagonal los completa con 1 y lo demás con 0.
np.tri(N = 5, M = 5)

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])